server:
  port: 10010
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-backend
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: laioj-backend-user-service
          uri: lb://laioj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: laioj-backend-question-service
          uri: lb://laioj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: laioj-backend-judge-service
          uri: lb://laioj-backend-judge-service
          predicates:
            - Path=/api/judge/**

#    gateway:
#      routes:
#        - id: laioj-backend-user-service # \u8DEF\u7531\u6807\u793A\uFF0C\u5FC5\u987B\u552F\u4E00
#          uri: lb://laioj-backend-user-service# \u8DEF\u7531\u7684\u76EE\u6807\u5730\u5740
#          predicates: # \u8DEF\u7531\u65AD\u8A00\uFF0C\u5224\u65AD\u8BF7\u6C42\u662F\u5426\u7B26\u5408\u89C4\u5219
#            - Path=/api/user/** # \u8DEF\u5F84\u65AD\u8A00\uFF0C\u5224\u65AD\u8DEF\u5F84\u662F\u5426\u662F\u4EE5/user\u5F00\u5934\uFF0C\u5982\u679C\u662F\u5219\u7B26\u5408
#        - id: laioj-backend-question-service # \u8DEF\u7531\u6807\u793A\uFF0C\u5FC5\u987B\u552F\u4E00
#          uri: lb://laioj-backend-question-service# \u8DEF\u7531\u7684\u76EE\u6807\u5730\u5740
#          predicates: # \u8DEF\u7531\u65AD\u8A00\uFF0C\u5224\u65AD\u8BF7\u6C42\u662F\u5426\u7B26\u5408\u89C4\u5219
#            - Path=/api/question/** # \u8DEF\u5F84\u65AD\u8A00\uFF0C\u5224\u65AD\u8DEF\u5F84\u662F\u5426\u662F\u4EE5/user\u5F00\u5934\uFF0C\u5982\u679C\u662F\u5219\u7B26\u5408
#        - id: laioj-backend-judge-service # \u8DEF\u7531\u6807\u793A\uFF0C\u5FC5\u987B\u552F\u4E00
#          uri: lb://laioj-backend-judge-service# \u8DEF\u7531\u7684\u76EE\u6807\u5730\u5740
#          predicates: # \u8DEF\u7531\u65AD\u8A00\uFF0C\u5224\u65AD\u8BF7\u6C42\u662F\u5426\u7B26\u5408\u89C4\u5219
#            - Path=/api/judge/** # \u8DEF\u5F84\u65AD\u8A00\uFF0C\u5224\u65AD\u8DEF\u5F84\u662F\u5426\u662F\u4EE5/user\u5F00\u5934\uFF0C\u5982\u679C\u662F\u5219\u7B26\u5408
knife4j:
  gateway:
    enabled: true
    # \u6307\u5B9A\u670D\u52A1\u53D1\u73B0\u7684\u6A21\u5F0F\u805A\u5408\u5FAE\u670D\u52A1\u6587\u6863
    strategy: discover
    discover:
      enabled: true
      # \u6307\u5B9A\u7248\u672C\u53F7(Swagger2|OpenAPI3)
      version : swagger2
